# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='github.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cgithub.proto\"\x1d\n\x07Request\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"\x14\n\x05Reply\x12\x0b\n\x03msg\x18\x01 \x01(\t2S\n\x07\x41\x63\x63ount\x12!\n\x0bGetUserName\x12\x08.Request\x1a\x06.Reply\"\x00\x12%\n\x0fSetUserPassword\x12\x08.Request\x1a\x06.Reply\"\x00\x32+\n\x04Gist\x12#\n\rGetPublicGist\x12\x08.Request\x1a\x06.Reply\"\x00\x32-\n\x04Repo\x12%\n\x0fGetLatestCommit\x12\x08.Request\x1a\x06.Reply\"\x00\x32/\n\x08\x43ommonDB\x12#\n\rGetCommonData\x12\x08.Request\x1a\x06.Reply\"\x00\x32+\n\x06\x43odeDB\x12!\n\x0bGetCodeData\x12\x08.Request\x1a\x06.Reply\"\x00\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='Request.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=45,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='Reply.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'github_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'github_pb2'
  # @@protoc_insertion_point(class_scope:Reply)
  })
_sym_db.RegisterMessage(Reply)



_ACCOUNT = _descriptor.ServiceDescriptor(
  name='Account',
  full_name='Account',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=69,
  serialized_end=152,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUserName',
    full_name='Account.GetUserName',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetUserPassword',
    full_name='Account.SetUserPassword',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACCOUNT)

DESCRIPTOR.services_by_name['Account'] = _ACCOUNT


_GIST = _descriptor.ServiceDescriptor(
  name='Gist',
  full_name='Gist',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=154,
  serialized_end=197,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPublicGist',
    full_name='Gist.GetPublicGist',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GIST)

DESCRIPTOR.services_by_name['Gist'] = _GIST


_REPO = _descriptor.ServiceDescriptor(
  name='Repo',
  full_name='Repo',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=199,
  serialized_end=244,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLatestCommit',
    full_name='Repo.GetLatestCommit',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPO)

DESCRIPTOR.services_by_name['Repo'] = _REPO


_COMMONDB = _descriptor.ServiceDescriptor(
  name='CommonDB',
  full_name='CommonDB',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  serialized_start=246,
  serialized_end=293,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCommonData',
    full_name='CommonDB.GetCommonData',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMONDB)

DESCRIPTOR.services_by_name['CommonDB'] = _COMMONDB


_CODEDB = _descriptor.ServiceDescriptor(
  name='CodeDB',
  full_name='CodeDB',
  file=DESCRIPTOR,
  index=4,
  serialized_options=None,
  serialized_start=295,
  serialized_end=338,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCodeData',
    full_name='CodeDB.GetCodeData',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CODEDB)

DESCRIPTOR.services_by_name['CodeDB'] = _CODEDB

# @@protoc_insertion_point(module_scope)
