# Generated by Django 3.0.2 on 2020-01-17 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zdoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('size', models.IntegerField()),
                ('owner', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
